# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}  # Ensures concurrency control by branch
  cancel-in-progress: false  # Avoids canceling ongoing deployments

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checks out your repository under $GITHUB_WORKSPACE

      - name: Setup Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0  # Specifies the Ruby version
          bundler-cache: true  # Caches installed gems between runs

      - name: Build Jekyll site
        run: |
          bundle install
          bundle exec jekyll build -d _site  # Builds your Jekyll site; adjust paths as needed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Uses a third-party action to deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Directory to publish

# Note: Adjust the ruby-version and publish_dir as per your project requirements.
